### ISSUE TITLE
多线程中调用会发生错误

### ISSUE THREAD

**Issue by backrock12** [jxnkwlp/UserDialogs2#1]
多线程中调用会发生Java错误提示
Can't toast on a thread that has not called Looper.prepare()

**Comment by jxnkwlp** [comment]
有示例代码吗？

**Comment by backrock12** [comment]
不好意思看错，不是多线程，是APP.XAML中的异常处理中。

`            TaskScheduler.UnobservedTaskException += (s, e) =>
              {
                  Passingwind.UserDialogs.UserDialogs.Instance.Toast("UnobservedTaskException" + e.Exception.Flatten());
              };`

调试

`02-16 09:19:29.771 E/mono-rt (11219): java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
02-16 09:19:29.771 E/mono-rt (11219): 	at android.os.Handler.<init>(Handler.java:200)
02-16 09:19:29.771 E/mono-rt (11219): 	at android.os.Handler.<init>(Handler.java:114)
02-16 09:19:29.771 E/mono-rt (11219): 	at android.widget.Toast$TN$2.<init>(Toast.java:379)
02-16 09:19:29.771 E/mono-rt (11219): 	at android.widget.Toast$TN.<init>(Toast.java:379)
02-16 09:19:29.771 E/mono-rt (11219): 	at android.widget.Toast.<init>(Toast.java:113)
02-16 09:19:29.771 E/mono-rt (11219): 	at android.widget.Toast.makeText(Toast.java:271)
`

**Comment by jxnkwlp** [comment]
试试 `Device.BeginInvokeOnMainThread `

            TaskScheduler.UnobservedTaskException += (s, e) =>
            { 
                 // 
                Device.BeginInvokeOnMainThread(() =>
                {
                    Passingwind.UserDialogs.UserDialogs.Instance.Toast("UnobservedTaskException" + e.Exception.Flatten());
                }); 
            };
